services:
  configserver:
    image: khandelwalsumit/config-server:1.0.0
    container_name: configserver
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - synergybank

  eurekaserver:
    image: khandelwalsumit/eureka-server:1.0.0
    container_name: eurekaserver
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - synergybank

  accounts:
    image: khandelwalsumit/accounts:1.0.0
    container_name: accounts
    ports:
      - 8080:8080
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: default
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - synergybank

  cards:
    image: khandelwalsumit/cards:1.0.0
    container_name: cards
    ports:
      - 9000:9000
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: default
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - synergybank

  loans:
    image: khandelwalsumit/loans:1.0.0
    container_name: loans
    ports:
      - 8090:8090
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: default
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - synergybank

  gatewayserver:
    image: khandelwalsumit/gateway-server:1.0.0
    container_name: gatewayserver
    ports:
      - 8072:8072
    depends_on:
      accounts:
        condition: service_healthy
      cards:
        condition: service_healthy
      loans:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: default
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - synergybank

networks:
  synergybank:
    driver: "bridge"