server:
  port: 8071
spring:
  application:
    name: "config-server"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri : "https://github.com/synergy2411/ms-config.git"
          timeout: 10
          default-label: main
          force-pull: true
          clone-on-start: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true